const express = require('express')
const router = express.Router()
const verifyJwt = require('../middleware/auth')
const auth = require('./auth')
const contest = require('./contests')
const squads = require('./squads')
const fixtures = require('./fixtures')
const userteams = require('./userTeams')
const users = require('./users')
const scorecard = require('./scorecard')
const paymentgateway = require('./paymentgateway')
const levelincome = require('./levelincome')
const banners = require('./banners')
const notifications = require('./notifications')
const { update_team_rank } = require('../services/sportsData')

router.use('/web-services', auth)
router.use('/web-services', verifyJwt, contest)
router.use('/web-services', squads)
router.use('/web-services', auth)
router.use('/web-services', fixtures)
router.use('/web-services', squads)
router.use('/web-services', squads)
router.use('/web-services', verifyJwt, users)
router.use('/web-services', userteams)
router.use('/web-services', scorecard)
router.use('/payment', paymentgateway)
router.use('/web-services',levelincome)
router.use('/web-services', verifyJwt, notifications)
router.use('/web-services', verifyJwt, banners)


module.exports = router
